apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- mysql-instance.yaml
- jira-configmap.yaml
- jira-ingress.yaml
- jira-service.yaml
- jira-statefulset.yaml
- jira-shared-pvc.yaml

vars:
- name: INGRESS_HOST
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: jira-config
  fieldref:
    fieldpath: data.ATL_PROXY_NAME
