apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

configMapGenerator:
- name: jira-config
  behavior: merge
  envs:
  - config.env

#patchesStrategicMerge:
#- config-map-new.yaml
