# Creates a cluster with one control-plane node and one worker node
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
kind: MaasCluster
metadata:
  name: maas-2
spec:
  dnsDomain: maas.sc
---
apiVersion: cluster.x-k8s.io/v1alpha4
kind: Cluster
metadata:
  name: maas-2
spec:
  clusterNetwork:
    services:
      cidrBlocks: ["10.96.0.0/12"]
    pods:
      cidrBlocks: ["192.168.0.0/16"]
    serviceDomain: "cluster.local"
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha4
    kind: KubeadmControlPlane
    name: maas-2-cp
    namespace: default
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
    kind: MaasCluster
    name: maas-2
    namespace: default
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
kind: MaasMachineTemplate
metadata:
  name: maas-2-cp
  namespace: default
spec:
  template:
    spec:
      minCPU: 2
      minMemory: 4096
      failureDomain: az2
      image: u-1804-0-k-11912-0
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha4
kind: KubeadmControlPlane
metadata:
  name: maas-2-cp
  namespace: default
spec:
  replicas: 1
  version: v1.19.12
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
      kind: MaasMachineTemplate
      name: maas-2-cp
      namespace: default
  kubeadmConfigSpec:
    clusterConfiguration: {}
    initConfiguration: {}
    joinConfiguration: {}
---
status:
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
kind: MaasMachineTemplate
metadata:
  name: maas-2-worker
  namespace: default
spec:
  template:
    spec:
      minCPU: 2
      minMemory: 4096
      failureDomain: az2
      image: u-1804-0-k-11912-0
---
apiVersion: cluster.x-k8s.io/v1alpha4
kind: MachineDeployment
metadata:
  name: maas-2-worker
  namespace: default
spec:
  clusterName: maas-2
  replicas: 1
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: maas-2
  template:
    spec:
      clusterName: maas-2
      version: 1.19.12
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha4
          kind: KubeadmConfigTemplate
          name: maas-2-worker
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
        kind: MaasMachineTemplate
        name: maas-2-worker
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha4
kind: KubeadmConfigTemplate
metadata:
  name: maas-2-worker
  namespace: default
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration: {}
