apiVersion: cluster.x-k8s.io/v1alpha4
kind: Cluster
metadata:
  name: eks-2
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha4
    kind: AWSManagedControlPlane
    name: eks-2-control-plane
  infrastructureRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha4
    kind: AWSManagedControlPlane
    name: eks-2-control-plane
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha4
kind: AWSManagedControlPlane
metadata:
  name: eks-2-control-plane
  namespace: default
spec:
  region: us-east-1
  sshKeyName: default
  version: v1.21
---
apiVersion: cluster.x-k8s.io/v1alpha4
kind: MachinePool
metadata:
  name: eks-2-pool-0
  namespace: default
spec:
  clusterName: eks-2
  replicas: 3
  template:
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: eks-2
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
        kind: AWSManagedMachinePool
        name: eks-2-pool-0
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
kind: AWSManagedMachinePool
metadata:
  name: eks-2-pool-0
  namespace: default
spec:
  scaling:
    minSize: 1
    maxSize: 5
